routes/web.php
<?php

Route::view('/', 'home.index')->name('home');

/*
    |--------------------------------------------------------------------------
    | Change language
    |--------------------------------------------------------------------------
    */
Route::get('lang/{lang}', 'ChangeLanguageController@changeLanguage')
    ->name('lang');
Route::get('firebase',  'Fire\FirebaseController@index');

Route::prefix('admin')->group(function (){
    /*
 |--------------------------------------------------------------------------
 | Auth Routes
 |--------------------------------------------------------------------------
 */
    Route::auth([
        'verify' => false,
        'register' => false
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lock and Unlock Account
    |--------------------------------------------------------------------------
    */
    Route::get('lock-account', 'Auth\LockAccountController@lockAccount')
        ->name('lock')
        ->middleware('auth');

    Route::post('unlock', 'Auth\LockAccountController@unLockAccount')
        ->name('unlock')
        ->middleware('auth');

    /*
    |--------------------------------------------------------------------------
    | App Routes
    |--------------------------------------------------------------------------
    */
    Route::middleware(['auth', 'verified', 'unlock'])->group(function () {

        Route::get('/', 'DashboardController@index')
            ->name('dashboard');

        // Users routes...

        Route::resource('users', 'Modules\UserController');

        Route::get('users-data', 'Modules\UserController@getData')
            ->name('users.data');

        // Permissions routes...

        Route::get('permissions', 'Modules\PermissionController@index')
            ->name('permissions.index');

        Route::get('permissions/data', 'Modules\PermissionController@getData')
            ->name('permissions.data');

        // Roles routes...

        Route::resource('roles', 'Modules\RoleController');

        Route::get('roles-data', 'Modules\RoleController@getData')
            ->name('roles.data');

        Route::get('roles/data/permissions/{id}', 'Modules\RoleController@permisionsRoles')
            ->name('roles.permissions.data');

        // Profile routes...
        Route::get('profile/{id}', 'ProfileController@index')
            ->name('profile');

        Route::put('profile/{id}/change-password', 'ProfileController@changePassword')
            ->name('profile.change-password');



        Route::get('users-licencia', 'Modules\UserController@licencia')
            ->name('users.licencia');

        Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
            \UniSharp\LaravelFilemanager\Lfm::routes();
        });

        Route::view('filemanager', 'filemanager.index')->name('filemanager');

        Route::get('pasajeros-datatable', 'DashboardController@dataTablePasajerosRegistrados')
            ->name('pasajeros-datatable');

        Route::get('conductores-datatable', 'DashboardController@dataTableConductoresRegistrados')
            ->name('conductores-datatable');

        Route::get('conductores-pendientes-datatable', 'DashboardController@dataTableConductoresPendientes')
            ->name('conductores-pendientes-datatable');
    });
});

app/Http/Controllers/Modules/PermissionController.php
<?php

namespace App\Http\Controllers\Modules;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use DataTables;

class PermissionController extends Controller
{
    /**
     * PermissionController constructor.
     */
    public function __construct()
    {
        $this->middleware('permission:permissions.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('modules.permissions.index');
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getData()
    {
        $permission = Permission::query();

        return DataTables::eloquent($permission)
            ->addColumn('created', 'modules.permissions.partials.created_at')
            ->rawColumns(['created'])
            ->toJson();
    }
}

app/Http/Controllers/Modules/RoleController.php
<?php

namespace App\Http\Controllers\Modules;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoleStoreRequest;
use App\Http\Requests\RoleUpdateRequest;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use DataTables;
use App\Helpers\RolesHelpers;

class RoleController extends Controller
{
    use RolesHelpers;

    /**
     * RoleController constructor.
     */
    public function __construct()
    {
        $this->middleware([
            'permission:roles.index',
            'permission:roles.create',
            'permission:roles.edit',
            'permission:roles.destroy',
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('modules.roles.index');
    }

    /**
     * Display Response Json data of te roles.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getData()
    {
        $role = Role::query();

        return DataTables::eloquent($role)
            ->addColumn('actions', 'modules.roles.partials.actions')
            ->addColumn('created', 'modules.roles.partials.created_at')
            ->rawColumns(['actions', 'created'])
            ->toJson();
    }

    /**
     * @param $id
     * @return mixed
     * @throws \Exception
     */
    public function permisionsRoles($id)
    {
        $role = Role::findById($id);

        $permissions = $role->permissions()->get();

        return DataTables::of($permissions)
            ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all()
            ->pluck('display_name', 'name');

        return view('modules.roles.create', [ 'permissions' => $permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(RoleStoreRequest $request)
    {
        return $this->createRole($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('modules.roles.show', ['role' => $role]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::all()
            ->pluck('display_name', 'name');

        $permissions_selected =  $role->permissions
            ->pluck('name')
            ->toArray();

        return view('modules.roles.edit', [ 'permissions' => $permissions, 'permissions_selected' => $permissions_selected, 'role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(RoleUpdateRequest $request, Role $role)
    {
        return $this->updateRole($request, $role);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Role $role)
    {
        switch ($role) {
            case $role->name == "administrator" || $role->name == "user":
                return $this->defaultRolesResponse();
                break;
            default:
                return $this->deleteRole($role);
                break;
        }
    }
}

app/Http/Controllers/Modules/UserController.php
<?php

namespace App\Http\Controllers\Modules;

use App\Helpers\UsersHelpers;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\Pais;
use App\Models\User;
use App\Models\TipoVehiculos;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use DataTables;

class UserController extends Controller
{
    use UsersHelpers;

    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->middleware('role:administrator');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('modules.users.index');
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getData()
    {
        $user = User::query();

        return DataTables::eloquent($user)
            ->addColumn('actions', 'modules.users.partials.actions')
            ->addColumn('image', 'modules.users.partials.image')
            ->addColumn('role', 'modules.users.partials.roles')
            ->rawColumns(['actions', 'image', 'status', 'role'])
            ->removeColumn('deleted_at')
            ->removeColumn('updated_at')
            ->toJson();
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all()->pluck('display_name', 'name');
        $paises = Pais::all()->pluck('nombre', 'id');

        return view('modules.users.create', [
            'roles' => $roles,
            'paises' => $paises,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        return $this->createUser($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $roles = Role::all()->pluck('display_name', 'name');

        return view('modules.users.show', ['user' => $user, 'roles' => $roles]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $tiposvehiculos = TipoVehiculos::all()->pluck('nombre', 'id');


        $roles = Role::all()->pluck('display_name', 'name');

        $paises = Role::all()->pluck('nombre', 'id');

        $role_selected = $user->roles->pluck('name')->toArray();

        $paises_seleccionados = $user->pais->pluck('id')->toArray();

        return view('modules.users.edit', [
            'user' => $user,
            'roles' => $roles,
            'role_selected' => $role_selected,
            'tiposvehiculos' => $tiposvehiculos,
            'paises' => $paises,
            'paises_seleccionados' => $paises_seleccionados
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        return $this->updateUser($user, $request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(User $user)
    {
        switch ($user) {
            case $user->email == "admin@admin.com":
                return $this->adminDeleteResponse();
                break;
            case $user->roles()->first()->name == "administrator";
                return $this->roleAdminAssigned();
            default:
                return $this->deleteUser($user);
                break;
        }
    }
}

resources/views/modules/roles/create.blade.php
@extends('layouts.app')

@section('page_title', __('modules.roles.roles-form.create-role'))

@section('breadcrumbs')
    {{ Breadcrumbs::render('roles.create') }}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title float-lg-left text-uppercase">
                        @lang('modules.roles.roles-form.roles-form-creation')
                    </h4>
                </div>
                <div class="card-body">
                    <div class="card-block">
                        @include('modules.roles.partials.form', ['id' => 'create-role-form', 'btn_text' => __('modules.roles.roles-form.save')])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')

    <script type="text/javascript">

        $("#create-role-form").on('submit', function (event) {
            event.preventDefault();

            $("#submit-button").attr("disabled", true);
            $("#name").removeClass('border-red');
            $("#description").removeClass('border-red');
            $("#permissions").removeClass('border-red');
            $("#error_name").addClass('display-hidden').text("");
            $("#error_description").addClass('display-hidden').text("");
            $("#error_permissions").addClass('display-hidden').text("");

            let formData = {
                name: $("#name").val(),
                description: $("#description").val(),
                permissions: $("#permissions").val()
            };

            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{{ route('roles.store') }}",
                type: "POST",
                dataType: "JSON",
                data: {
                    name: formData.name,
                    description: formData.description,
                    permissions: formData.permissions
                }
            }).success(function (response) {
                $("#submit-button").attr("disabled", false);
                $("#create-role-form")[0].reset();
                $('#permissions').val('').trigger('change');
                console.log(response);
                swal({
                    icon: 'success',
                    title: response.title,
                    text: response.message
                });
            }).error(function (response) {
                $("#submit-button").attr("disabled", false);
                console.error(response);
                swal({
                    icon: 'error',
                    title: response.responseJSON.message,
                    text: response.statusText
                });

                let error_name = response.responseJSON.errors.name;
                let error_description = response.responseJSON.errors.description;
                let error_permissions = response.responseJSON.errors.permissions;

                if (error_name) {
                    console.error(error_name.toString());
                    $("#name").addClass('border-red');
                    $("#error_name").removeClass('display-hidden').text(error_name.toString());
                }

                if (error_description) {
                    console.error(error_description.toString());
                    $("#description").addClass('border-red');
                    $("#error_description").removeClass('display-hidden').text(error_description.toString());
                }

                if (error_permissions) {
                    console.error(error_permissions.toString());
                    $("#permissions").addClass('border-red');
                    $("#error_permissions").removeClass('display-hidden').text(error_permissions.toString());
                }

            })

        })

    </script>
@endpush

resources/views/modules/roles/edit.blade.php
@extends('layouts.app')

@section('page_title', __('modules.roles.roles-edit')." ". $role->name)

@section('breadcrumbs')
    {{ Breadcrumbs::render('roles.edit', $role) }}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title float-lg-left text-uppercase">
                        @lang('modules.roles.roles-form.roles-form-edit')
                    </h4>
                </div>
                <div class="card-body">
                    <div class="card-block">
                        @include('modules.roles.partials.form', ['id' => 'edit-role-form', "role" => $role, 'permissions' => $permissions, 'permissions_selected' => $permissions_selected, 'btn_text' => __('modules.roles.roles-form.save-changes')])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')

<script type="text/javascript">

    $("#edit-role-form").on('submit', function (event) {
        event.preventDefault();

        $("#submit-button").attr("disabled", true);
        $("#name").removeClass('border-red');
        $("#description").removeClass('border-red');
        $("#permissions").removeClass('border-red');
        $("#error_name").addClass('display-hidden').text("");
        $("#error_description").addClass('display-hidden').text("");
        $("#error_permissions").addClass('display-hidden').text("");

        let formData = {
            name: $("#name").val(),
            description: $("#description").val(),
            permissions: $("#permissions").val()
        };

        swal({
            title: "@lang('modules.roles.roles-messages.are-you-sure')",
            text: "@lang('modules.roles.roles-messages.text-confirm-update')",
            icon: 'warning',
            buttons: {
                cancel: {
                    text: "@lang('modules.roles.roles-messages.cancel')",
                    value: false,
                    visible: true,
                    className: "btn btn-danger mr-1",
                    closeModal: true
                },
                confirm: {
                    text: "@lang('modules.roles.roles-messages.confirm-update')",
                    value: true,
                    visible: true,
                    className: "btn btn-success",
                    closeModal: true
                }
            },
        }).then((result) => {

            if(result === true) {
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url: "{{ route('roles.update', $role->id) }}",
                    type: "PUT",
                    dataType: "JSON",
                    data: {
                        name: formData.name,
                        description: formData.description,
                        permissions: formData.permissions
                    }
                }).success(function (response) {
                    $("#submit-button").attr("disabled", false);
                    console.log(response);
                    swal({
                        icon: 'success',
                        title: response.title,
                        text: response.message
                    });
                }).error(function (response) {
                    $("#submit-button").attr("disabled", false);
                    console.error(response);
                    swal({
                        icon: 'error',
                        title: response.responseJSON.message,
                        text: response.statusText
                    });

                    let error_name = response.responseJSON.errors.name;
                    let error_description = response.responseJSON.errors.description;
                    let error_permissions = response.responseJSON.errors.permissions;

                    if (error_name) {
                        console.error(error_name.toString());
                        $("#name").addClass('border-red');
                        $("#error_name").removeClass('display-hidden').text(error_name.toString());
                    }

                    if (error_description) {
                        console.error(error_description.toString());
                        $("#description").addClass('border-red');
                        $("#error_description").removeClass('display-hidden').text(error_description.toString());
                    }

                    if (error_permissions) {
                        console.error(error_permissions.toString());
                        $("#permissions").addClass('border-red');
                        $("#error_permissions").removeClass('display-hidden').text(error_permissions.toString());
                    }

                });
            } else {
                $("#submit-button").attr("disabled", false);
                swal({
                    title: "@lang('modules.roles.roles-messages.canceled')",
                    text: "@lang('modules.roles.roles-messages.no-save-changes')",
                    icon: "error"
                });
            }
        });
    });

</script>
@endpush

resources/views/modules/roles/index.blade.php
@extends('layouts.app')

@section('page_title', __('modules.roles.roles-header'))

@section('breadcrumbs')
    {{ Breadcrumbs::render('roles.index') }}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title float-lg-left text-uppercase">
                        @lang('modules.roles.roles-title')
                    </h4>
                    @can('roles.create')
                        <a href="{{ route('roles.create') }}" class="btn btn-primary float-lg-right text-uppercase">
                            @lang('modules.roles.roles-create')
                        </a>
                    @endcan
                </div>
                <div class="card-body">
                    <div class="card-block">
                        @include('modules.roles.partials.table')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">

        let dataTable;

        $(function () {
            dataTable = $("#roles-table").DataTable({
                processing: true,
                ajax: {
                    url: "{{ route('roles.data') }}",
                    type: "GET"
                },
                columns: [
                    { data: "id"},
                    { data: "display_name" },
                    { data: "description" },
                    { data: "created" },
                    { data: "actions", orderable: false, searchable: false },
                ],
                language: {
                    "emptyTable":     "@lang('datatables.emptyTable')",
                    "info":           "@lang('datatables.info')",
                    "infoEmpty":      "@lang('datatables.infoEmpty')",
                    "infoFiltered":   "@lang('datatables.infoFiltered')",
                    "infoPostFix":    "",
                    "infoThousands":  ",",
                    "lengthMenu":     "@lang('datatables.lengthMenu')",
                    "loadingRecords": "@lang('datatables.loadingRecords')",
                    "processing":     "@lang('datatables.processing')",
                    "search":         "@lang('datatables.search')",
                    "zeroRecords":    "@lang('datatables.zeroRecords')",
                    "paginate": {
                        "first":    "@lang('datatables.paginate.first')",
                        "last":     "@lang('datatables.paginate.last')",
                        "next":     "@lang('datatables.paginate.next')",
                        "previous": "@lang('datatables.paginate.previous')"
                    },
                    "aria": {
                        "sortAscending":  "@lang('datatables.aria.sortAscending')",
                        "sortDescending": "@lang('datatables.aria.sortDescending')"
                    }
                }
            });
        });

        function destroy(id) {
            swal({
              title: "@lang('modules.roles.roles-messages.are-you-sure')",
              text: "@lang('modules.roles.roles-messages.text-confirm-delete')",
              icon: 'warning',
              buttons: {
                  cancel: {
                      text: "@lang('modules.roles.roles-messages.cancel')",
                      value: false,
                      visible: true,
                      className: "btn btn-danger mr-1",
                      closeModal: true
                  },
                  confirm: {
                      text: "@lang('modules.roles.roles-messages.confirm-delete')",
                      value: true,
                      visible: true,
                      className: "btn btn-success",
                      closeModal: true
                  }
                },
            }).then((result) => {
                if (result === true) {
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        type: "DELETE",
                        url: "roles/" + id,
                        dataType: "JSON",
                    }).success(function (response) {

                        dataTable.ajax.reload();

                        swal({
                            icon: 'success',
                            title: response.title,
                            text: response.message
                        });
                    }).error(function (response) {
                        console.log(response);
                        swal({
                            icon: 'error',
                            title: response.responseJSON.title,
                            text: response.responseJSON.message
                        });
                    });
                } else if (result === false) {
                  swal({
                      title: "@lang('modules.roles.roles-messages.canceled')",
                      text: "@lang('modules.roles.roles-messages.no-deleted')",
                      icon: "error"
                  });
                }
            });
        }
    </script>
@endpush