routes/web.php
<?php

Route::view('/', 'home.index')->name('home');

/*
    |--------------------------------------------------------------------------
    | Change language
    |--------------------------------------------------------------------------
    */
Route::get('lang/{lang}', 'ChangeLanguageController@changeLanguage')
    ->name('lang');
Route::get('firebase',  'Fire\FirebaseController@index');

Route::prefix('admin')->group(function (){
    /*
 |--------------------------------------------------------------------------
 | Auth Routes
 |--------------------------------------------------------------------------
 */
    Route::auth([
        'verify' => false,
        'register' => false
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lock and Unlock Account
    |--------------------------------------------------------------------------
    */
    Route::get('lock-account', 'Auth\LockAccountController@lockAccount')
        ->name('lock')
        ->middleware('auth');

    Route::post('unlock', 'Auth\LockAccountController@unLockAccount')
        ->name('unlock')
        ->middleware('auth');

    /*
    |--------------------------------------------------------------------------
    | App Routes
    |--------------------------------------------------------------------------
    */
    Route::middleware(['auth', 'verified', 'unlock'])->group(function () {

        Route::get('/', 'DashboardController@index')
            ->name('dashboard');

        // Users routes...

        Route::resource('users', 'Modules\UserController');

        Route::get('users-data', 'Modules\UserController@getData')
            ->name('users.data');

        // Permissions routes...

        Route::get('permissions', 'Modules\PermissionController@index')
            ->name('permissions.index');

        Route::get('permissions/data', 'Modules\PermissionController@getData')
            ->name('permissions.data');

        // Roles routes...

        Route::resource('roles', 'Modules\RoleController');

        Route::get('roles-data', 'Modules\RoleController@getData')
            ->name('roles.data');

        Route::get('roles/data/permissions/{id}', 'Modules\RoleController@permisionsRoles')
            ->name('roles.permissions.data');

        // Profile routes...
        Route::get('profile/{id}', 'ProfileController@index')
            ->name('profile');

        Route::put('profile/{id}/change-password', 'ProfileController@changePassword')
            ->name('profile.change-password');



        Route::get('users-licencia', 'Modules\UserController@licencia')
            ->name('users.licencia');

        Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
            \UniSharp\LaravelFilemanager\Lfm::routes();
        });

        Route::view('filemanager', 'filemanager.index')->name('filemanager');

        Route::get('pasajeros-datatable', 'DashboardController@dataTablePasajerosRegistrados')
            ->name('pasajeros-datatable');

        Route::get('conductores-datatable', 'DashboardController@dataTableConductoresRegistrados')
            ->name('conductores-datatable');

        Route::get('conductores-pendientes-datatable', 'DashboardController@dataTableConductoresPendientes')
            ->name('conductores-pendientes-datatable');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Traits\HasRoles;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, HasRoles, HasApiTokens;

    const APROBADO = true;
    const RECHAZADO = false;
    const CONFORMADO = true;
    const NOCONFIRMADO = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar','dni', 'surname',
        'direccion', 'aprobado', 'confirmado', 'tlf', 'pais_id', 'api_token',
        'tipo_usuario', 'foto', 'observacion'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Set the user's passwords.
     *
     * @param  string  $password
     * @return void
     */

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function pais()
    {
        return $this->belongsTo(Pais::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function documentos()
    {
        return $this->hasMany(Documentos::class);
    }

}

app/Http/Controllers/Modules/PermissionController.php
<?php

namespace App\Http\Controllers\Modules;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use DataTables;

class PermissionController extends Controller
{
    /**
     * PermissionController constructor.
     */
    public function __construct()
    {
        $this->middleware('permission:permissions.index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('modules.permissions.index');
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getData()
    {
        $permission = Permission::query();

        return DataTables::eloquent($permission)
            ->addColumn('created', 'modules.permissions.partials.created_at')
            ->rawColumns(['created'])
            ->toJson();
    }
}

app/Http/Controllers/Modules/RoleController.php
<?php

namespace App\Http\Controllers\Modules;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoleStoreRequest;
use App\Http\Requests\RoleUpdateRequest;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use DataTables;
use App\Helpers\RolesHelpers;

class RoleController extends Controller
{
    use RolesHelpers;

    /**
     * RoleController constructor.
     */
    public function __construct()
    {
        $this->middleware([
            'permission:roles.index',
            'permission:roles.create',
            'permission:roles.edit',
            'permission:roles.destroy',
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('modules.roles.index');
    }

    /**
     * Display Response Json data of te roles.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getData()
    {
        $role = Role::query();

        return DataTables::eloquent($role)
            ->addColumn('actions', 'modules.roles.partials.actions')
            ->addColumn('created', 'modules.roles.partials.created_at')
            ->rawColumns(['actions', 'created'])
            ->toJson();
    }

    /**
     * @param $id
     * @return mixed
     * @throws \Exception
     */
    public function permisionsRoles($id)
    {
        $role = Role::findById($id);

        $permissions = $role->permissions()->get();

        return DataTables::of($permissions)
            ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all()
            ->pluck('display_name', 'name');

        return view('modules.roles.create', [ 'permissions' => $permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(RoleStoreRequest $request)
    {
        return $this->createRole($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('modules.roles.show', ['role' => $role]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::all()
            ->pluck('display_name', 'name');

        $permissions_selected =  $role->permissions
            ->pluck('name')
            ->toArray();

        return view('modules.roles.edit', [ 'permissions' => $permissions, 'permissions_selected' => $permissions_selected, 'role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(RoleUpdateRequest $request, Role $role)
    {
        return $this->updateRole($request, $role);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Role $role)
    {
        switch ($role) {
            case $role->name == "administrator" || $role->name == "user":
                return $this->defaultRolesResponse();
                break;
            default:
                return $this->deleteRole($role);
                break;
        }
    }
}

app/Http/Controllers/Modules/UserController.php
<?php

namespace App\Http\Controllers\Modules;

use App\Helpers\UsersHelpers;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\Pais;
use App\Models\User;
use App\Models\TipoVehiculos;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use DataTables;

class UserController extends Controller
{
    use UsersHelpers;

    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->middleware('role:administrator');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('modules.users.index');
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getData()
    {
        $user = User::query();

        return DataTables::eloquent($user)
            ->addColumn('actions', 'modules.users.partials.actions')
            ->addColumn('image', 'modules.users.partials.image')
            ->addColumn('role', 'modules.users.partials.roles')
            ->rawColumns(['actions', 'image', 'status', 'role'])
            ->removeColumn('deleted_at')
            ->removeColumn('updated_at')
            ->toJson();
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all()->pluck('display_name', 'name');
        $paises = Pais::all()->pluck('nombre', 'id');

        return view('modules.users.create', [
            'roles' => $roles,
            'paises' => $paises,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        return $this->createUser($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $roles = Role::all()->pluck('display_name', 'name');

        return view('modules.users.show', ['user' => $user, 'roles' => $roles]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $tiposvehiculos = TipoVehiculos::all()->pluck('nombre', 'id');


        $roles = Role::all()->pluck('display_name', 'name');

        $paises = Role::all()->pluck('nombre', 'id');

        $role_selected = $user->roles->pluck('name')->toArray();

        $paises_seleccionados = $user->pais->pluck('id')->toArray();

        return view('modules.users.edit', [
            'user' => $user,
            'roles' => $roles,
            'role_selected' => $role_selected,
            'tiposvehiculos' => $tiposvehiculos,
            'paises' => $paises,
            'paises_seleccionados' => $paises_seleccionados
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        return $this->updateUser($user, $request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(User $user)
    {
        switch ($user) {
            case $user->email == "admin@admin.com":
                return $this->adminDeleteResponse();
                break;
            case $user->roles()->first()->name == "administrator";
                return $this->roleAdminAssigned();
            default:
                return $this->deleteUser($user);
                break;
        }
    }
}

resources/views/modules/users/create.blade.php
@extends('layouts.app')

@section('page_title', __('modules.users.users-form.create-user'))

@section('breadcrumbs')
    {{ Breadcrumbs::render('users.create') }}
@endsection

@section('content')
    @if (session('message'))
        <div class="alert alert-success no-border mb-2" role="alert">
            <strong>{{ session('message') }}</strong>
        </div>
    @endif
    @include('modules.users.partials.form', [
        'paises' => $paises,
        'roles' => $roles,
        'method' => 'POST',
        'btn_text' => 'Registrar usuario',
        'route' => 'users.store'
    ])
@endsection

@push('scripts')
    <script src="{{ asset('js/dropzone.js') }}"></script>
    <script>
        $("#my-dropzone").dropzone();
    </script>
@endpush

resources/views/modules/users/edit.blade.php
@extends('layouts.app')

@section('page_title', __("modules.users.users-edit") ." ". $user->name)

@section('breadcrumbs')
    {{ Breadcrumbs::render('users.edit', $user) }}
@endsection

@section('content')
    @include('modules.users.partials.form', [
        'paises' => $paises, 'roles' => $roles, 'method' => 'PUT',
        'btn_text' => 'Actualizar usuario'
    ])
@endsection

@push('scripts')
    <script type="text/javascript">

        $("#user_form_update").on('submit', function (event) {
            event.preventDefault();
            $("#submit-button").attr("disabled", true);
            $("#name").removeClass('border-red');
            $("#email").removeClass('border-red');
            $("#role").removeClass('border-red');
            $("#error_name").addClass('display-hidden').text("");
            $("#error_email").addClass('display-hidden').text("");
            $("#error_role").addClass('display-hidden').text("");

            let form_data = {
                name: $("#name").val(),
                email: $("#email").val(),
                surname: $("#surname").val(),
                role: $("#role").val(),
                direccion: $("#direccion").val(),
                aprobado: $("#aprobado").val(),
                confirmado: $("#confirmado").val(),
                tlf: $("#tlf").val(),
                pais: $("#pais").val()
            };

            swal({
                title: "@lang('modules.users.users-messages.are-you-sure')",
                text: "@lang('modules.users.users-messages.text-confirm-update')",
                icon: 'warning',
                buttons: {
                    cancel: {
                        text: "@lang('modules.users.users-messages.cancel')",
                        value: false,
                        visible: true,
                        className: "btn btn-danger mr-1",
                        closeModal: true
                    },
                    confirm: {
                        text: "@lang('modules.users.users-messages.confirm-update')",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                },
            }).then((result) => {
                if (result === true) {
                    $.ajax({
                        type: "PUT",
                        url: "{{ route('users.update', $user->id) }}",
                        data: {
                            name: form_data.name,
                            email: form_data.email,
                            role: form_data.role,
                            surname: form_data.surname,
                            direccion: form_data.direccion,
                            aprobado: form_data.aprobado,
                            tlf: form_data.tlf,
                            pais: form_data.pais
                        },
                        dataType: "JSON",
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    }).success(function (response) {
                        $("#submit-button").attr("disabled", false);
                        console.log(response);
                        swal({
                            icon: 'success',
                            title: response.title,
                            text: response.message
                        });
                    }).error(function (response) {
                        $("#submit-button").attr("disabled", false);
                        console.log(response);
                        swal({
                            icon: 'error',
                            title: response.responseJSON.message,
                            text: response.statusText
                        });

                        let error_name = response.responseJSON.errors.name;
                        let error_email = response.responseJSON.errors.email;
                        let error_role = response.responseJSON.errors.role;

                        if (error_name) {
                            console.error(error_name.toString());
                            $("#name").addClass('border-red');
                            $("#error_name").removeClass('display-hidden').text(error_name.toString());
                        }

                        if (error_email) {
                            console.error(error_email.toString());
                            $("#email").addClass('border-red');
                            $("#error_email").removeClass('display-hidden').text(error_email.toString());
                        }

                        if (error_role) {
                            console.error(error_role.toString());
                            $("#role").addClass('border-red');
                            $("#error_role").removeClass('display-hidden').text(error_role.toString());
                        }
                    });
                } else {
                    $("#submit-button").attr("disabled", false);
                    swal({
                        title: "@lang('modules.users.users-messages.canceled')",
                        text: "@lang('modules.users.users-messages.no-save-changes')",
                        icon: "error"
                    });
                };
            });
        });
        $('#file2').fileupload({
          url: "{{ route('users.licencia') }}",
          dataType: 'json',
          start: function(){
                $(".loaderFile", "#licencia").fadeIn();

          },
          done: function (e, data) {
            $("#resultado2").html(data.result.msj);
            $(".loaderFile", "#licencia").fadeOut();
          }
      });
    </script>
@endpush

resources/views/modules/users/index.blade.php
@extends('layouts.app')

@section('page_title', __('modules.users.users-header'))

@section('breadcrumbs')
    {{ Breadcrumbs::render('users.index') }}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title float-lg-left text-uppercase">
                        @lang('modules.users.users-title')
                    </h4>
                    @can('users.create')
                        <a href="{{ route('users.create') }}" class="btn btn-primary float-lg-right text-uppercase">
                            @lang('modules.users.users-create')
                        </a>
                    @endcan
                </div>
                <div class="card-body">
                    <div class="card-block">
                        @include('modules.users.partials.table')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">

        let dataTable;

        // Read users...
        $(function(){

            dataTable = $("#users-table").DataTable({
                processing: true,
                ajax: {
                    url: "{{ route('users.data') }}",
                    type: "GET"
                },
                columns: [
                    { data: "image", orderable: false, searchable: false },
                    { data: "name" },
                    { data: "role" },
                    { data: "actions", orderable: false, searchable: false },
                ],
                language: {
                    "emptyTable":     "@lang('datatables.emptyTable')",
                    "info":           "@lang('datatables.info')",
                    "infoEmpty":      "@lang('datatables.infoEmpty')",
                    "infoFiltered":   "@lang('datatables.infoFiltered')",
                    "infoPostFix":    "",
                    "infoThousands":  ",",
                    "lengthMenu":     "@lang('datatables.lengthMenu')",
                    "loadingRecords": "@lang('datatables.loadingRecords')",
                    "processing":     "@lang('datatables.processing')",
                    "search":         "@lang('datatables.search')",
                    "zeroRecords":    "@lang('datatables.zeroRecords')",
                    "paginate": {
                        "first":    "@lang('datatables.paginate.first')",
                        "last":     "@lang('datatables.paginate.last')",
                        "next":     "@lang('datatables.paginate.next')",
                        "previous": "@lang('datatables.paginate.previous')"
                    },
                    "aria": {
                        "sortAscending":  "@lang('datatables.aria.sortAscending')",
                        "sortDescending": "@lang('datatables.aria.sortDescending')"
                    }
                }
            });

        });

        // Delete users
        function destroy(id) {

            swal({
                title: "@lang('modules.users.users-messages.are-you-sure')",
                text: "@lang('modules.users.users-messages.text-confirm-delete')",
                icon: 'warning',
                buttons: {
                    cancel: {
                        text: "@lang('modules.users.users-messages.cancel')",
                        value: false,
                        visible: true,
                        className: "btn btn-danger mr-1",
                        closeModal: true
                    },
                    confirm: {
                        text: "@lang('modules.users.users-messages.confirm-delete')",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                },
            }).then((result) => {

                if (result == true) {
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        type: "DELETE",
                        url: "/admin/users/" + id,
                        dataType: "JSON",
                    }).success(function (response) {

                        dataTable.ajax.reload();
                        swal({
                            icon: 'success',
                            title: response.title,
                            text: response.message
                        });
                    }).error(function (response) {
                        console.log(response);
                        swal({
                            icon: 'error',
                            title: response.responseJSON.title,
                            text: response.responseJSON.message
                        });
                    });
                } else if (result === false) {
                    swal({
                        title: "@lang('modules.users.users-messages.canceled')",
                        text: "@lang('modules.users.users-messages.no-deleted')",
                        icon: "error"
                    });
                }
            });
        }
    </script>
@endpush